spring:
  datasource:
    driver-class-name:com.mysql.cj.jdbc.Driver
    url:jdbc:mysql://localhost:3306/airbnb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:root
    password:codeS123!@#
  jpa:
    hibernate:
      ddl-auto:create
    properties:
      hibernate:
      format_sql:true

logging:
  level:
    org.hibernate.SQL:debug
    org.hibernate.type:trace
